on:
  push:
    branches:
      - master
name: on push

jobs:

  build:
    name: generate and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./
        env:
          USER_SITE_REPOSITORY: mrncstt/mrncstt.github.io
          GITHUB_TOKEN: ${{ secrets.JEKYLL_PAT }}
